-- Users table
CREATE TABLE IF NOT EXISTS USERS(
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(30) NOT NULL UNIQUE,
    PASSWORD TEXT NOT NULL
);

-- Sessions Table
CREATE TABLE  IF NOT EXISTS SESSIONS (
    ID SERIAL PRIMARY KEY,
    USERID INT NOT NULL REFERENCES USERS(ID) ON DELETE CASCADE,
    TOKENHASH TEXT NOT NULL,
    ISSUED_AT TIMESTAMPTZ NOT NULL,
    EXPIRES_AT TIMESTAMPTZ NOT NULL,
    UNIQUE(USERID)
);

-- Tasks table
-- CREATE TYPE STATUS_TYPES AS ENUM('COMPLETED','ONGOING','PENDING');
-- CREATE TYPE PRIORITY_TYPES AS ENUM('LOW','MEDIUM','HIGH');
CREATE TABLE  IF NOT EXISTS TASKS(
    ID SERIAL PRIMARY KEY,
    ASSIGNED_BY INT NOT NULL REFERENCES USERS(ID) ON DELETE CASCADE,
    ASSIGNED_TO INT NOT NULL REFERENCES USERS(ID) ON DELETE CASCADE,
    ASSIGNED_AT TIMESTAMPTZ NOT NULL,
    ACCEPTED_AT TIMESTAMPTZ,
    DEADLINE TIMESTAMPTZ NOT NULL,
    STATUS STATUS_TYPES NOT NULL DEFAULT 'PENDING',
    PRIORITY PRIORITY_TYPES NOT NULL DEFAULT 'LOW'
);

-- Notifications Table
-- CREATE TABLE  IF NOT EXISTS NOTIFICATIONS();